version: "3"

services:
    smile_music_py:
        restart: always
        build:
            context: .
            dockerfile: DockerfilePy
        container_name: "smile_music_py"
        tty: true
        env_file:
            - ./hiddendata/smile_music_postgres.env
            - ./hiddendata/smile_music_py.env

volumes:
    database:
        driver: local