version: "3"

services:
    smile_music_db:
        image: postgres:13.2
        restart: always
        container_name: "smile_music_db"
        env_file:
            - ./local.env
        ports:
            - "5432:5432"
        volumes:
            - ./database:/var/lib/postgresql/data
            - ./initdb:/docker-entrypoint-initdb.d

    smile_music_py:
        restart: always
        build:
            context: .
        container_name: "smile_music_py"
        command: forever -c python smile_music.py
        tty: true
        depends_on:
            - smile_music_db
        env_file:
            - ./local.env
        volumes:
            - ./python:/opt

volumes:
    database:
        driver: local