version: "3"

services:
    smile_music_db:
        image: postgres:13.2
        restart: always
        container_name: "smile_music_db"
        environment:
            - POSTGRES_HOST
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
            - POSTGRES_PORT
        ports:
            - "5432:5432"
        volumes:
            - ./database:/var/lib/postgresql/data
            - ./initdb:/docker-entrypoint-initdb.d

    smile_music_py:
        restart: always
        build:
            context: .
        container_name: "smile_music_py"
        command: forever -c python smile_music.py
        tty: true
        depends_on:
            - smile_music_db
        environment:
            - POSTGRES_HOST
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
            - POSTGRES_PORT
            - POSTGRES_DATABASE_URL
            - SMILEMUSIC_DISCORD_TOKEN
            - SMILEMUSIC_PREFIX
            - SMILEMUSIC_ENV
        volumes:
            - ./python:/opt

volumes:
    database:
        driver: local